/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medmanager;

/**
 *
 * @author Will
 */
public class CadastroEquipamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroUtensiliosMedicos
     */
    public CadastroEquipamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        descricao1 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        concentracao = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        modoUso = new javax.swing.JLabel();
        formato = new javax.swing.JLabel();
        quantidade = new javax.swing.JLabel();
        validade = new javax.swing.JLabel();
        txtConcentracao = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtValidade = new javax.swing.JTextField();
        txtQty = new javax.swing.JSpinner();
        slctTipo = new java.awt.Choice();
        slctModoUso = new java.awt.Choice();
        slctFormato = new java.awt.Choice();
        btnLimpar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lbDescricaoEquip = new javax.swing.JLabel();
        lbNomeEquip = new javax.swing.JLabel();
        txtNomeEquip = new javax.swing.JTextField();
        lbTipoEquip = new javax.swing.JLabel();
        lbQuantidadeEquip = new javax.swing.JLabel();
        lbValidadeEquip = new javax.swing.JLabel();
        lbLoteEquip = new javax.swing.JLabel();
        txtQuantidadeEquip = new javax.swing.JSpinner();
        txtValidadeEquip = new javax.swing.JTextField();
        txtLoteEquip = new javax.swing.JTextField();
        btLimparEquip = new javax.swing.JButton();
        btCancelarEquip = new javax.swing.JButton();
        btSalvarEquip = new javax.swing.JButton();
        slctTipoEquip = new java.awt.Choice();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(340, 294));

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        descricao1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        descricao1.setText("Informações do Medicamento");

        nome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nome.setText("Nome");

        concentracao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        concentracao.setText("Concentração: ");

        tipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tipo.setText("Tipo: ");

        modoUso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modoUso.setText("Mode de Uso: ");

        formato.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        formato.setText("Formato:");

        quantidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quantidade.setText("Quantidade: ");

        validade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        validade.setText("Validade: ");

        txtConcentracao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtConcentracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConcentracaoActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtValidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtQty.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        slctTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        slctModoUso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        slctFormato.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnLimpar.setBackground(new java.awt.Color(255, 255, 153));
        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");

        btnSalvar.setBackground(new java.awt.Color(102, 255, 102));
        btnSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(descricao1)
                        .addGap(54, 54, 54))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(concentracao)
                                    .addComponent(nome)
                                    .addComponent(tipo)
                                    .addComponent(modoUso)
                                    .addComponent(formato)
                                    .addComponent(quantidade)
                                    .addComponent(validade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome)
                                    .addComponent(txtConcentracao)
                                    .addComponent(txtValidade)
                                    .addComponent(slctTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(slctFormato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(slctModoUso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(btnLimpar)
                                .addGap(46, 46, 46)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar)))
                        .addContainerGap())))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descricao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concentracao)
                    .addComponent(txtConcentracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipo)
                    .addComponent(slctTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modoUso)
                    .addComponent(slctModoUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formato)
                    .addComponent(slctFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidade)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validade)
                    .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpar)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );

        lbDescricaoEquip.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbDescricaoEquip.setText("Informações do Equipamento");

        lbNomeEquip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeEquip.setText("Nome:");

        txtNomeEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lbTipoEquip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbTipoEquip.setText("Tipo:");

        lbQuantidadeEquip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbQuantidadeEquip.setText("Quantidade:");

        lbValidadeEquip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbValidadeEquip.setText("Validade:");

        lbLoteEquip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbLoteEquip.setText("Lote:");

        txtQuantidadeEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtValidadeEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtLoteEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btLimparEquip.setBackground(new java.awt.Color(255, 255, 153));
        btLimparEquip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btLimparEquip.setText("Limpar");

        btCancelarEquip.setBackground(new java.awt.Color(255, 102, 102));
        btCancelarEquip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btCancelarEquip.setText("Cancelar");

        btSalvarEquip.setBackground(new java.awt.Color(102, 255, 102));
        btSalvarEquip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btSalvarEquip.setText("Salvar");

        slctTipoEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbQuantidadeEquip)
                            .addComponent(lbTipoEquip)
                            .addComponent(lbNomeEquip)
                            .addComponent(lbLoteEquip)
                            .addComponent(lbValidadeEquip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQuantidadeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNomeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtValidadeEquip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoteEquip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slctTipoEquip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLimparEquip)
                        .addGap(50, 50, 50)
                        .addComponent(btCancelarEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btSalvarEquip)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDescricaoEquip)
                .addGap(60, 60, 60))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 162, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 162, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDescricaoEquip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeEquip)
                    .addComponent(txtNomeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTipoEquip)
                    .addComponent(slctTipoEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidadeEquip)
                    .addComponent(txtQuantidadeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValidadeEquip)
                    .addComponent(txtValidadeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoteEquip)
                    .addComponent(txtLoteEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparEquip)
                    .addComponent(btCancelarEquip)
                    .addComponent(btSalvarEquip))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 132, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 132, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConcentracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConcentracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcentracaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarEquip;
    private javax.swing.JButton btLimparEquip;
    private javax.swing.JButton btSalvarEquip;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel concentracao;
    private javax.swing.JLabel descricao1;
    private javax.swing.JLabel formato;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel lbDescricaoEquip;
    private javax.swing.JLabel lbLoteEquip;
    private javax.swing.JLabel lbNomeEquip;
    private javax.swing.JLabel lbQuantidadeEquip;
    private javax.swing.JLabel lbTipoEquip;
    private javax.swing.JLabel lbValidadeEquip;
    private javax.swing.JLabel modoUso;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel quantidade;
    private java.awt.Choice slctFormato;
    private java.awt.Choice slctModoUso;
    private java.awt.Choice slctTipo;
    private java.awt.Choice slctTipoEquip;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextField txtConcentracao;
    private javax.swing.JTextField txtLoteEquip;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeEquip;
    private javax.swing.JSpinner txtQty;
    private javax.swing.JSpinner txtQuantidadeEquip;
    private javax.swing.JTextField txtValidade;
    private javax.swing.JTextField txtValidadeEquip;
    private javax.swing.JLabel validade;
    // End of variables declaration//GEN-END:variables
}
