/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medmanager;

/**
 *
 * @author Janaina
 */
public class CadastroMedicamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroMedicamento
     */
    public CadastroMedicamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descricao = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        concentracao = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        modoUso = new javax.swing.JLabel();
        formato = new javax.swing.JLabel();
        quantidade = new javax.swing.JLabel();
        validade = new javax.swing.JLabel();
        txtConcentracao = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtValidade = new javax.swing.JTextField();
        txtQty = new javax.swing.JSpinner();
        slctTipo = new java.awt.Choice();
        slctModoUso = new java.awt.Choice();
        slctFormato = new java.awt.Choice();
        btnLimpar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        descricao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        descricao.setText("Informações do Medicamento");

        nome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nome.setText("Nome");

        concentracao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        concentracao.setText("Concentração: ");

        tipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tipo.setText("Tipo: ");

        modoUso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modoUso.setText("Mode de Uso: ");

        formato.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        formato.setText("Formato:");

        quantidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quantidade.setText("Quantidade: ");

        validade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        validade.setText("Validade: ");

        txtConcentracao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtConcentracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConcentracaoActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtValidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtQty.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        slctTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        slctModoUso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        slctFormato.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnLimpar.setBackground(new java.awt.Color(255, 255, 153));
        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");

        btnSalvar.setBackground(new java.awt.Color(102, 255, 102));
        btnSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addComponent(descricao)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(concentracao)
                                    .addComponent(nome)
                                    .addComponent(tipo)
                                    .addComponent(modoUso)
                                    .addComponent(formato)
                                    .addComponent(quantidade)
                                    .addComponent(validade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome)
                                    .addComponent(txtConcentracao)
                                    .addComponent(txtValidade)
                                    .addComponent(slctTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(slctFormato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(slctModoUso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpar)
                                .addGap(46, 46, 46)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concentracao)
                    .addComponent(txtConcentracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipo)
                    .addComponent(slctTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modoUso)
                    .addComponent(slctModoUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formato)
                    .addComponent(slctFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidade)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validade)
                    .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpar)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConcentracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConcentracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcentracaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel concentracao;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel formato;
    private javax.swing.JLabel modoUso;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel quantidade;
    private java.awt.Choice slctFormato;
    private java.awt.Choice slctModoUso;
    private java.awt.Choice slctTipo;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextField txtConcentracao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JSpinner txtQty;
    private javax.swing.JTextField txtValidade;
    private javax.swing.JLabel validade;
    // End of variables declaration//GEN-END:variables
}
