/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medmanager;

/**
 *
 * @author Janaina
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPricipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaDeTrabalho = new medmanager.AreaDeTrabalho();
        menuPricipal = new javax.swing.JMenuBar();
        menuProdutos = new javax.swing.JMenu();
        menuItemMedicamento = new javax.swing.JMenuItem();
        menuItemUtensilios = new javax.swing.JMenuItem();
        menuItemProdutosGerais = new javax.swing.JMenuItem();
        menuPessoas = new javax.swing.JMenu();
        menuItemFuncionario = new javax.swing.JMenuItem();
        menuItemPaciente = new javax.swing.JMenuItem();
        menuItemUsuario = new javax.swing.JMenuItem();
        menuItemFornecedor = new javax.swing.JMenuItem();
        menuItemMedico = new javax.swing.JMenuItem();
        menuEntragas = new javax.swing.JMenu();
        menuItemEntregaExterna = new javax.swing.JMenuItem();
        menuItemEntregaInterna = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuAtributos = new javax.swing.JMenu();
        itemMenuFormato = new javax.swing.JMenuItem();
        itemMenuModoUso = new javax.swing.JMenuItem();
        itemMenuTipo = new javax.swing.JMenuItem();
        itemMenuNivelAcesso = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaDeTrabalho.setToolTipText("");
        getContentPane().add(areaDeTrabalho, java.awt.BorderLayout.CENTER);

        menuProdutos.setText("Produtos");

        menuItemMedicamento.setText("Medicamentos");
        menuItemMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMedicamentoActionPerformed(evt);
            }
        });
        menuProdutos.add(menuItemMedicamento);

        menuItemUtensilios.setText("Utensilios Medicos");
        menuItemUtensilios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUtensiliosActionPerformed(evt);
            }
        });
        menuProdutos.add(menuItemUtensilios);

        menuItemProdutosGerais.setText("Produtos Gerais");
        menuItemProdutosGerais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutosGeraisActionPerformed(evt);
            }
        });
        menuProdutos.add(menuItemProdutosGerais);

        menuPricipal.add(menuProdutos);

        menuPessoas.setText("Pessoas");

        menuItemFuncionario.setText("Funcionario");
        menuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionarioActionPerformed(evt);
            }
        });
        menuPessoas.add(menuItemFuncionario);

        menuItemPaciente.setText("Paciente");
        menuItemPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPacienteActionPerformed(evt);
            }
        });
        menuPessoas.add(menuItemPaciente);

        menuItemUsuario.setText("Usuario");
        menuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUsuarioActionPerformed(evt);
            }
        });
        menuPessoas.add(menuItemUsuario);

        menuItemFornecedor.setText("Fornecedor");
        menuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFornecedorActionPerformed(evt);
            }
        });
        menuPessoas.add(menuItemFornecedor);

        menuItemMedico.setText("Medico");
        menuItemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMedicoActionPerformed(evt);
            }
        });
        menuPessoas.add(menuItemMedico);

        menuPricipal.add(menuPessoas);

        menuEntragas.setText("Entregas");

        menuItemEntregaExterna.setText("Entrega Externa");
        menuEntragas.add(menuItemEntregaExterna);

        menuItemEntregaInterna.setText("Entrega Interna");
        menuEntragas.add(menuItemEntregaInterna);

        menuPricipal.add(menuEntragas);

        menuRelatorios.setText("Relatorios");
        menuPricipal.add(menuRelatorios);

        menuAtributos.setText("Atributos");

        itemMenuFormato.setText("Formato");
        menuAtributos.add(itemMenuFormato);

        itemMenuModoUso.setText("Modo de Uso");
        menuAtributos.add(itemMenuModoUso);

        itemMenuTipo.setText("Tipo");
        itemMenuTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuTipoActionPerformed(evt);
            }
        });
        menuAtributos.add(itemMenuTipo);

        itemMenuNivelAcesso.setText("Nivel de Acesso");
        itemMenuNivelAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuNivelAcessoActionPerformed(evt);
            }
        });
        menuAtributos.add(itemMenuNivelAcesso);

        menuPricipal.add(menuAtributos);

        menuSair.setText("Sair");
        menuPricipal.add(menuSair);

        setJMenuBar(menuPricipal);

        setSize(new java.awt.Dimension(558, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMedicamentoActionPerformed
        areaDeTrabalho.abrirCadastroMedicamento();
    }//GEN-LAST:event_menuItemMedicamentoActionPerformed

    private void menuItemUtensiliosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUtensiliosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemUtensiliosActionPerformed

    private void menuItemProdutosGeraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutosGeraisActionPerformed
        areaDeTrabalho.abrirGerenciarProduto();
    }//GEN-LAST:event_menuItemProdutosGeraisActionPerformed

    private void menuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionarioActionPerformed
        areaDeTrabalho.abrirGerenciarFuncionario();
    }//GEN-LAST:event_menuItemFuncionarioActionPerformed

    private void menuItemPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPacienteActionPerformed
        areaDeTrabalho.abrirGerenciarPaciente();
    }//GEN-LAST:event_menuItemPacienteActionPerformed

    private void menuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemUsuarioActionPerformed

    private void menuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFornecedorActionPerformed
        areaDeTrabalho.abrirGerenciarFornecedor();
    }//GEN-LAST:event_menuItemFornecedorActionPerformed

    private void menuItemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMedicoActionPerformed
        areaDeTrabalho.abrirGerenciarMedico();
    }//GEN-LAST:event_menuItemMedicoActionPerformed

    private void itemMenuNivelAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuNivelAcessoActionPerformed
        areaDeTrabalho.abrirGerenciarNivelAcesso();
    }//GEN-LAST:event_itemMenuNivelAcessoActionPerformed

    private void itemMenuTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuTipoActionPerformed
        areaDeTrabalho.abrirGerenciarTipoMedicamento();
    }//GEN-LAST:event_itemMenuTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private medmanager.AreaDeTrabalho areaDeTrabalho;
    private javax.swing.JMenuItem itemMenuFormato;
    private javax.swing.JMenuItem itemMenuModoUso;
    private javax.swing.JMenuItem itemMenuNivelAcesso;
    private javax.swing.JMenuItem itemMenuTipo;
    private javax.swing.JMenu menuAtributos;
    private javax.swing.JMenu menuEntragas;
    private javax.swing.JMenuItem menuItemEntregaExterna;
    private javax.swing.JMenuItem menuItemEntregaInterna;
    private javax.swing.JMenuItem menuItemFornecedor;
    private javax.swing.JMenuItem menuItemFuncionario;
    private javax.swing.JMenuItem menuItemMedicamento;
    private javax.swing.JMenuItem menuItemMedico;
    private javax.swing.JMenuItem menuItemPaciente;
    private javax.swing.JMenuItem menuItemProdutosGerais;
    private javax.swing.JMenuItem menuItemUsuario;
    private javax.swing.JMenuItem menuItemUtensilios;
    private javax.swing.JMenu menuPessoas;
    private javax.swing.JMenuBar menuPricipal;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
